// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $community_index from "./routes/community/index.tsx";
import * as $cookbook_index from "./routes/cookbook/index.tsx";
import * as $dash_index from "./routes/dash/index.tsx";
import * as $dash_stats from "./routes/dash/stats.tsx";
import * as $dash_users_id_ from "./routes/dash/users/[id].tsx";
import * as $dash_users_index from "./routes/dash/users/index.tsx";
import * as $events_index from "./routes/events/index.ts";
import * as $events_upcoming from "./routes/events/upcoming.ts";
import * as $index from "./routes/index.tsx";
import * as $projects_index from "./routes/projects/index.tsx";
import * as $qa_id_hide from "./routes/qa/[id]/hide.ts";
import * as $qa_id_index from "./routes/qa/[id]/index.ts";
import * as $qa_id_vote from "./routes/qa/[id]/vote.ts";
import * as $qa_ask from "./routes/qa/ask.tsx";
import * as $qa_index from "./routes/qa/index.tsx";
import * as $qa_user_votes from "./routes/qa/user-votes.ts";
import * as $setup_index from "./routes/setup/index.tsx";
import * as $stories_slug_ from "./routes/stories/[slug].tsx";
import * as $stories_feed from "./routes/stories/feed.ts";
import * as $stories_index from "./routes/stories/index.tsx";
import * as $users_id_index from "./routes/users/[id]/index.ts";
import * as $users_id_questions from "./routes/users/[id]/questions.ts";
import * as $users_index from "./routes/users/index.ts";
import * as $users_me from "./routes/users/me.ts";
import * as $videos_index from "./routes/videos/index.tsx";
import * as $_common_islands_infinite_scroller_list from "./routes/(common)/(_islands)/infinite-scroller-list.tsx";
import * as $_common_islands_share from "./routes/(common)/(_islands)/share.tsx";
import * as $_common_islands_shortcuts from "./routes/(common)/(_islands)/shortcuts.tsx";
import * as $dash_islands_chart from "./routes/dash/(_islands)/chart.tsx";
import * as $qa_islands_list from "./routes/qa/(_islands)/list.tsx";
import * as $qa_islands_listitem_hide from "./routes/qa/(_islands)/listitem-hide.tsx";
import * as $qa_islands_listitem_vote from "./routes/qa/(_islands)/listitem-vote.tsx";
import * as $stories_islands_list from "./routes/stories/(_islands)/list.tsx";
import * as $videos_islands_list from "./routes/videos/(_islands)/list.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/community/index.tsx": $community_index,
    "./routes/cookbook/index.tsx": $cookbook_index,
    "./routes/dash/index.tsx": $dash_index,
    "./routes/dash/stats.tsx": $dash_stats,
    "./routes/dash/users/[id].tsx": $dash_users_id_,
    "./routes/dash/users/index.tsx": $dash_users_index,
    "./routes/events/index.ts": $events_index,
    "./routes/events/upcoming.ts": $events_upcoming,
    "./routes/index.tsx": $index,
    "./routes/projects/index.tsx": $projects_index,
    "./routes/qa/[id]/hide.ts": $qa_id_hide,
    "./routes/qa/[id]/index.ts": $qa_id_index,
    "./routes/qa/[id]/vote.ts": $qa_id_vote,
    "./routes/qa/ask.tsx": $qa_ask,
    "./routes/qa/index.tsx": $qa_index,
    "./routes/qa/user-votes.ts": $qa_user_votes,
    "./routes/setup/index.tsx": $setup_index,
    "./routes/stories/[slug].tsx": $stories_slug_,
    "./routes/stories/feed.ts": $stories_feed,
    "./routes/stories/index.tsx": $stories_index,
    "./routes/users/[id]/index.ts": $users_id_index,
    "./routes/users/[id]/questions.ts": $users_id_questions,
    "./routes/users/index.ts": $users_index,
    "./routes/users/me.ts": $users_me,
    "./routes/videos/index.tsx": $videos_index,
  },
  islands: {
    "./routes/(common)/(_islands)/infinite-scroller-list.tsx": $_common_islands_infinite_scroller_list,
    "./routes/(common)/(_islands)/share.tsx": $_common_islands_share,
    "./routes/(common)/(_islands)/shortcuts.tsx": $_common_islands_shortcuts,
    "./routes/dash/(_islands)/chart.tsx": $dash_islands_chart,
    "./routes/qa/(_islands)/list.tsx": $qa_islands_list,
    "./routes/qa/(_islands)/listitem-hide.tsx": $qa_islands_listitem_hide,
    "./routes/qa/(_islands)/listitem-vote.tsx": $qa_islands_listitem_vote,
    "./routes/stories/(_islands)/list.tsx": $stories_islands_list,
    "./routes/videos/(_islands)/list.tsx": $videos_islands_list,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
