name: Continuous Integration

on:
  push:
    branches:
      - "**"

  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "**"

  # schedule:
  #   - cron: "18 21 * * 6"

jobs:
  integration:
    name: CI Checks for Deno ${{ matrix.deno-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read # Needed to clone the repository

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        deno-version:
          - 1.41.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Runs pre-commit rules
        uses: pre-commit/action@v3
        with:
          extra_args: "--all-files"

      - name: Create lcov file
        if: matrix.os == 'ubuntu-latest'
        run: deno task cov:gen

      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          name: ${{ matrix.os }}
          files: cov_profile.lcov
